### ISSUE TITLE
[FollowTurtlebot] Migration to Robotics Academy v2.3

### ISSUE THREAD

**Issue by iamarkaj** [JdeRobot/RoboticsAcademy#806]
TODO
- [x] It is currently using roombaROS from [CustomRobots](https://github.com/JdeRobot/CustomRobots), this needs to be fixed because using the same robot will reduce the difference between version 2.3 and version 2.1 (done in #805)
- [x] Update readme, webpage and add clouds (done in #835)
- [x] Update RoboticsAcademy/RoboticsAcademy.html to include follow turtlebot (done in #840)
- [x] More buttons must be added to control the ground robot (done in #849)
- [x] Modify launch file to use turtlebot xacro from drone_assets package instead local duplicated file (done in #857)
- [x] Update developer launching instructions inside RoboticsAcademy/exercises/drone_cat_mouse/web-template/README.md and RoboticsAcademy/exercises/follow_turtlebot/web-template/README.md since it no longer uses gzweb (done in #863)
- [ ] Fix Reset button. Drone flies randomly and crashes sometimes. Maybe due to lat and long. [This](https://github.com/mavlink/mavros/blob/7b7790026f710c2888ff28cc181e46b6b94acdbd/mavros/scripts/mavcmd) may be useful.
- [x] Fix console.print() and print error messages of the student's code
- [ ] Update YT video inside RoboticsAcademy/RoboticsAcademy.html to correctly demonstrate web-template based v2.3 of this exercise

**Comment by dgvsnl** [comment]
I want to contibute to this issue

**Comment by pariaspe** [comment]
Done in #805. RADI 0.3.14 will include exercise dependencies.

Some tasks remaining:
- Add buttons to start, pause and reset turtlebot
- Improve gazebo world to look nicer
- Modify launch file to use turtlebot xacro from drone_assets package instead local duplicated file

Credits to @iamarkaj for the migration

**Comment by pariaspe** [comment]
Some other tasks to do as @iamarkaj said [[1]](https://github.com/JdeRobot/RoboticsAcademy/pull/835#issuecomment-815394833):

1. Update developer launching instructions inside RoboticsAcademy/exercises/drone_cat_mouse/web-template/README.md and RoboticsAcademy/exercises/follow_turtlebot/web-template/README.md since it no longer uses gzweb
2. Update RoboticsAcademy/RoboticsAcademy.html to include follow turtlebot

**Comment by trunc8** [comment]
> Some other tasks to do as @iamarkaj said [[1]](https://github.com/JdeRobot/RoboticsAcademy/pull/835#issuecomment-815394833):
> 
> 1. Update developer launching instructions inside RoboticsAcademy/exercises/drone_cat_mouse/web-template/README.md and RoboticsAcademy/exercises/follow_turtlebot/web-template/README.md since it no longer uses gzweb
> 2. Update RoboticsAcademy/RoboticsAcademy.html to include follow turtlebot

Task 2 solved in PR #840.
Additional questions for Task 1:
1) What would the updated developer launching steps be? Should it guide how to mount a local volume into the Docker container for testing and debugging?
2) In what scenario would a user check the README inside the web-template directories? We might have to make changes at fewer places if we only maintain the guidelines in the docs. What is your opinion on this @pariaspe?

**Comment by pariaspe** [comment]
Hi @trunc8,

> Task 2 solved in PR #840.
> Additional questions for Task 1:
> 
>  1. What would the updated developer launching steps be? Should it guide how to mount a local volume into the Docker container for testing and debugging?

The developer launching steps are the instructions to launch the exercise without the manager.py, ussually by running different docker bashes.

>   2. In what scenario would a user check the README inside the web-template directories? We might have to make changes at fewer places if we only maintain the guidelines in the docs. What is your opinion on this @pariaspe?

READMEs are for developers, but yes, you are right, keeping instructions in different locations is a headeach.

**Comment by jmplaza** [comment]
The launching instructions should be in the webpage for each exercise itself, on GitHub Pages. The users and developers should see (and update) them there. Maybe we should move the RADI-launch there...

**Comment by dgvsnl** [comment]
hello sir,
So basically for each exercises, we have to add RADI-launch.. for directly
launching web-templetes.

Question-  were to add RADI,
-- directly to each exercise folder
                OR
-- Add separate folder were all the RADI launch files are...

**Comment by trunc8** [comment]
Can you clarify what you mean by "adding RADI" and "adding RADI-launch"?

**Comment by dgvsnl** [comment]
OKay, I m on it.

**Comment by dgvsnl** [comment]
I mean, we want the launching instruction of each exercise on the github
pages directly, RIGHT!!

So were should i append installation information --- in readme.md file?

**Comment by pariaspe** [comment]
Hello @dgvsnl, we already have the running instructions in github pages for each exercise

**Comment by jmplaza** [comment]
The exercise is ready and works with RADI 2.4.3
